packages:
  - 'server'

allowBuilds:
  '@apollo/protobufjs': true
  '@nestjs/core': true
  '@parcel/watcher': set this to true or false
  unrs-resolver: false

ignoredBuiltDependencies:
  - '@parcel/watcher'